- name: Update Ubuntu packages
  hosts: all
  become: true
  tasks:
  - name: Accept repository changes explicitly
    shell: apt-get update --allow-releaseinfo-change
    become: true
    ignore_errors: true
  - name: Check for GPG key error during apt update
    shell: apt-get update
    become: true
    register: apt_update_result
    ignore_errors: true
  - name: Update apt cache
    apt:
      update_cache: true
      lock_timeout: 120
  - name: Upgrade all packages except wazuh-agent
    shell: apt-mark hold wazuh-agent && apt-get dist-upgrade -y && apt-mark unhold
      wazuh-agent
    become: true
  - name: Remove APT lock files
    file:
      path: '{{ item }}'
      state: absent
    become: true
    loop:
    - /var/lib/apt/lists/lock
    - /var/cache/apt/archives/lock
    - /var/lib/dpkg/lock
