- name: Update Ubuntu packages
  hosts: all
  become: yes
  tasks:
    - name: Accept repository changes explicitly
      become: yes
      shell: apt-get update -- become: yes
      shell: |
        wget -qO - https://www.mongodb.org/static/pgp/server-3.2.asc | apt-key add -
      when: "'EXPKEYSIG D68FA50FEA312927' in apt_update_result.stderr"
      ignore_errors: yes

    - name: Update apt cache
      apt:
        update_cache: yes
        lock_timeout: 120

    - name: Upgrade all packages except wazuh-agent
      become: yes
      shell: |
        apt-mark hold wazuh-agent
        apt-get dist-upgrade -y
        apt-mark unhold wazuh-agent

    - name: Remove APT lock files
      become: yes
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/apt/lists/lock
        - /var/cache/apt/archives/lock
        - /var/lib/dpkg/lock
      shell: apt-get update --allow-releaseinfo-change
      ignore_errors: yes

    - name: Check for GPG key error during apt update
      become: yes
      shell: apt-get update
      register: apt_update_result
      ignore_errors: yes

    - name: Update MongoDB GPG key if error is detected
