---
- name: Update Ubuntu server
  hosts: all
  become: yes
  tasks:
    - name: Remove APT lock files
      file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/apt/lists/lock
        - /var/cache/apt/archives/lock
        - /var/lib/dpkg/lock
        - /var/lib/dpkg/lock-frontend

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Upgrade all packages
      command: apt-get dist-upgrade -y
      become: yes

    - name: Autoremove unused packages
      command: apt-get autoremove -y
      become: yes
